adm/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control, never_cache

urlpatterns = [
    url(r'^contratos/OT/$', login_required(views.OTList.as_view()), name='ot-list'),
    url(r'^contratos/OT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTCreate.as_view())),
                                   name='ot-create'),
    url(r'^contratos/OT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTUpdate.as_view())),
                                               name='ot-update'),
    url(r'^contratos/OT-ML/$', login_required(views.OTMLList.as_view()), name='otml-list'),
    url(r'^contratos/OT-ML/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTMLCreate.as_view())),
                                      name='otml-create'),
    url(r'^contratos/OT-ML/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTMLUpdate.as_view())),
                                                  name='otml-update'),
    url(r'^contratos/SOT/$', login_required(views.SOTList.as_view()), name='sot-list'),
    url(r'^contratos/SOT/viewSOT/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.viewSOT)), name='sot-viewSOT'),
    url(r'^contratos/SOT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SOTCreate.as_view())),
                                    name='sot-create'),
    url(r'^contratos/SOT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SOTUpdate.as_view())),
                                                name='sot-update'),
    url(r'^contratos/RUT/$', login_required(views.RUTList.as_view()), name='rut-list'),
    url(r'^contratos/RUT/viewRUT/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.viewRUT)), name='rut-viewRUT'),
    url(r'^contratos/RUT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.RUTCreate.as_view())),
                                    name='rut-create'),
    url(r'^contratos/RUT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.RUTUpdate.as_view())),
                                                name='rut-update'),
    url(r'^contratos/SI/$', login_required(views.SIList.as_view()), name='si-list'),
    url(r'^contratos/SI/viewSI/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.viewSI)), name='si-viewSI'),
    url(r'^contratos/SI/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SICreate.as_view())),
                                   name='si-create'),
    url(r'^contratos/SI/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SIUpdate.as_view())),
                                               name='si-update'),
    url(r'^contratos/SI/(create|update/\d+)/OT_(?P<area>(LIA|LIM1|LIM2|LIM3|LIM4|LIM5|LIM6|EXT|DES|SIS|MEC|ML|CAL))/$', views.filterOT, name='filter-ot'),
    url(r'^presup/$', login_required(views.PresupuestoList.as_view()), name='presup-list'),
    url(r'^presup/viewWord/(?P<pk>\d+)/(?P<template>\w+)/$', never_cache(login_required(views.viewWord)), name='presup-viewWord'),
    #url(r'^presup/actBtn/(?P<pk>\d+)/$', 'adm.views.actualizar_precios', name='presup-actBtn'),
    url(r'^presup/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PresupuestoUpdate.as_view())),
                                         name='presup-update'),
    url(r'^presup/update/(?P<pk>\d+)/revision/', views.createRevision, name='presup-revision'),
    url(r'^presup/update/(?P<pk>\d+)/rollback/', views.rollBackRevision, name='presup-rollback'),
    url(r'^presup/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PresupuestoCreate.as_view())),
                             name='presup-create'),

    url(r'^presup/get_user/$', views.get_user, name='user-getdata'),
    url(r'^ofertatec/$', login_required(views.OfertaTecList.as_view()), name='ofertatec-list'),
    url(r'^ofertatec/delete/(?P<pk>\d+)/$', login_required(views.OfertaTecDelete.as_view()), name='ofertatec-delete'),
    url(r'^ofertatec/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OfertaTecUpdate.as_view())),
                                            name='ofertatec-update'),
    url(r'^ofertatec/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OfertaTecCreate.as_view())),
                                name='ofertatec-create'),

    url(r'^usuarios/$', login_required(views.UsuarioList.as_view()), name='usuarios-list'),
    url(r'^usuarios/delete/(?P<pk>\d+)/$', login_required(views.UsuarioDelete.as_view()), name='usuarios-delete'),
    url(r'^usuarios/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioUpdate.as_view())),
                                           name='usuarios-update'),
    url(r'^usuarios/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioCreate.as_view())),
                               name='usuarios-create'),
    url(r'^usuarios/create-modal/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioCreateModal.as_view())),
                               name='usuarios-create-modal'),
    url(r'^usuarios/update-modal/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioUpdateModal.as_view())),
                               name='usuarios-update-modal'),
    url(r'^pdt/$', login_required(views.PDTList.as_view()), name='pdt-list'),
    url(r'^pdt/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PDTCreate.as_view())),
                               name='pdt-create'),
    url(r'^pdt/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PDTUpdate.as_view())),
                                            name='pdt-update'),
    url(r'^pdt/detail/(?P<pk>\d+)/$', never_cache(login_required(views.PDTDetail.as_view())), name='pdt-detail'),
    url(r'^pdt/viewPDF/(?P<pk>\d+)/$', never_cache(views.pdtToPdf), name='pdt-viewPDF'),
    url(r'^pdt/viewXLS/(?P<pk>\d+)/$', never_cache(views.pdtToXls), name='pdt-viewXLS'),
    url(r'^contactos/create-modal/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.ContactoCreateModal.as_view())),
                                             name='contactos-create-modal'),
    url(r'^direcciones/create-modal/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.DireccionUsuarioCreateModal.as_view())),
                                             name='direcciones-create-modal'),
    url(r'^contactos/update-modal/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.ContactoUpdateModal.as_view())),
                                             name='contactos-update-modal'),
    url(r'^ajax/contactos/$', views.load_contactos, name='ajax_load_contactos'),
    url(r'^ajax/localides/$', views.load_localidades, name='ajax_load_localidades'),
    url(r'^ajax/direcciones/$', views.load_direcciones, name='ajax_load_direcciones'),
]

intiSoft/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .forms import MyAuthenticationForm
from . import views as myViews
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^lab/', include('lab.urls', namespace="lab")),
    url(r'^adm/', include('adm.urls', namespace="adm")),
    url(r'^recent_activity/', include('activity_log.urls', namespace="activity_log")),
    url(r'^login/$', views.login,
        {'template_name': 'intiSoft/login.html',
        'authentication_form': MyAuthenticationForm},
        name='user-login'),
    url(r'^logout/$', views.logout,
        {'template_name': 'intiSoft/logout.html'},
        name='user-logout'),
    url('^$', myViews.index, name='index'),
    url(r'^profile/(?P<pk>\d+)/$', myViews.ProfileView.as_view(),
        name='user-profile'),
    url(r'^ofertatec_autocomplete/', myViews.ofertatec_autocomplete, name='ofertatec_autocomplete'),
    #url(r'^simple-autocomplete/', include('simple_autocomplete.urls', namespace='simple_autocomplete'))
]

lab/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control

urlpatterns = [
    url(r'^turnos/$', login_required(views.TurnoList.as_view()), name='turnos-list'),
    url(r'^turnos/calendar/LIA/$', login_required(views.LIACalendarView.as_view()), name='LIA-calendar'),
    url(r'^turnos/calendar/LIA/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.LIACalendarView.as_view()), name='LIA-calendar'),
    url(r'^turnos/calendar/LIM1/$', login_required(views.LIM1CalendarView.as_view()), name='LIM1-calendar'),
    url(r'^turnos/calendar/LIM1/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.LIM1CalendarView.as_view()), name='LIM1-calendar'),
    url(r'^turnos/calendar/LIM2/$', login_required(views.LIM2CalendarView.as_view()), name='LIM2-calendar'),
    url(r'^turnos/calendar/LIM2/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.LIM2CalendarView.as_view()), name='LIM2-calendar'),
    url(r'^turnos/calendar/LIM3/$', login_required(views.LIM3CalendarView.as_view()), name='LIM3-calendar'),
    url(r'^turnos/calendar/LIM3/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.LIM3CalendarView.as_view()), name='LIM3-calendar'),
    url(r'^turnos/calendar/LIM4/$', login_required(views.LIM4CalendarView.as_view()), name='LIM4-calendar'),
    url(r'^turnos/calendar/LIM4/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.LIM4CalendarView.as_view()), name='LIM4-calendar'),
    url(r'^turnos/calendar/LIM5/$', login_required(views.LIM5CalendarView.as_view()), name='LIM5-calendar'),
    url(r'^turnos/calendar/LIM5/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.LIM5CalendarView.as_view()), name='LIM5-calendar'),
    url(r'^turnos/calendar/LIM6/$', login_required(views.LIM6CalendarView.as_view()), name='LIM6-calendar'),
    url(r'^turnos/calendar/LIM6/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.LIM6CalendarView.as_view()), name='LIM6-calendar'),
    url(r'^turnos/calendar/EXT/$', login_required(views.EXTCalendarView.as_view()), name='EXT-calendar'),
    url(r'^turnos/calendar/EXT/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.EXTCalendarView.as_view()), name='EXT-calendar'),
    url(r'^turnos/calendar/TICS/$', login_required(views.TICSCalendarView.as_view()), name='TICS-calendar'),
    url(r'^turnos/calendar/TICS/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.TICSCalendarView.as_view()), name='TICS-calendar'),
    url(r'^turnos/calendar/DES/$', login_required(views.DESCalendarView.as_view()), name='DES-calendar'),
    url(r'^turnos/calendar/DES/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.DESCalendarView.as_view()), name='DES-calendar'),
    url(r'^turnos/calendar/CAL/$', login_required(views.CALCalendarView.as_view()), name='CAL-calendar'),
    url(r'^turnos/calendar/CAL/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.CALCalendarView.as_view()), name='CAL-calendar'),
    url(r'^turnos/calendar/MEC/$', login_required(views.MECCalendarView.as_view()), name='MEC-calendar'),
    url(r'^turnos/calendar/MEC/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.MECCalendarView.as_view()), name='MEC-calendar'),
    url(r'^turnos/calendar/ML/$', login_required(views.MLCalendarView.as_view()), name='ML-calendar'),
    url(r'^turnos/calendar/ML/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', login_required(views.MLCalendarView.as_view()), name='ML-calendar'),
    url(r'^turnos/LIA/$', login_required(views.LIAList.as_view()), name='LIA-list'),
    url(r'^turnos/LIM1/$', login_required(views.LIM1List.as_view()), name='LIM1-list'),
    url(r'^turnos/LIM2/$', login_required(views.LIM2List.as_view()), name='LIM2-list'),
    url(r'^turnos/LIM3/$', login_required(views.LIM3List.as_view()), name='LIM3-list'),
    url(r'^turnos/LIM4/$', login_required(views.LIM4List.as_view()), name='LIM4-list'),
    url(r'^turnos/LIM5/$', login_required(views.LIM5List.as_view()), name='LIM5-list'),
    url(r'^turnos/LIM6/$', login_required(views.LIM6List.as_view()), name='LIM6-list'),
    url(r'^turnos/EXT/$', login_required(views.EXTList.as_view()), name='EXT-list'),
    url(r'^turnos/TICS/$', login_required(views.TICSList.as_view()), name='TICS-list'),
    url(r'^turnos/DES/$', login_required(views.DESList.as_view()), name='DES-list'),
    url(r'^turnos/CAL/$', login_required(views.CALList.as_view()), name='CAL-list'),
    url(r'^turnos/MEC/$', login_required(views.MECList.as_view()), name='MEC-list'),
    url(r'^turnos/ML/$', login_required(views.MLList.as_view()), name='ML-list'),
    url(r'^turnos/LIA/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIACreate.as_view())),
                                 name='LIA-create'),
    url(r'^turnos/LIM1/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM1Create.as_view())),
                                  name='LIM1-create'),
    url(r'^turnos/LIM2/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM2Create.as_view())),
                                  name='LIM2-create'),
    url(r'^turnos/LIM3/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM3Create.as_view())),
                                  name='LIM3-create'),
    url(r'^turnos/LIM4/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM4Create.as_view())),
                                  name='LIM4-create'),
    url(r'^turnos/LIM5/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM5Create.as_view())),
                                  name='LIM5-create'),
    url(r'^turnos/LIM6/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM6Create.as_view())),
                                  name='LIM6-create'),
    url(r'^turnos/EXT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.EXTCreate.as_view())),
                                 name='EXT-create'),
    url(r'^turnos/TICS/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.TICSCreate.as_view())),
                                 name='TICS-create'),
    url(r'^turnos/DES/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.DESCreate.as_view())),
                                 name='DES-create'),
    url(r'^turnos/CAL/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.CALCreate.as_view())),
                                 name='CAL-create'),
    url(r'^turnos/MEC/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.MECCreate.as_view())),
                                 name='MEC-create'),
    url(r'^turnos/ML/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.MLCreate.as_view())),
                                name='ML-create'),
    url(r'^turnos/LIA/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIAUpdate.as_view())),
                                             name='LIA-update'),
    url(r'^turnos/LIM1/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM1Update.as_view())),
                                              name='LIM1-update'),
    url(r'^turnos/LIM2/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM2Update.as_view())),
                                              name='LIM2-update'),
    url(r'^turnos/LIM3/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM3Update.as_view())),
                                              name='LIM3-update'),
    url(r'^turnos/LIM4/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM4Update.as_view())),
                                              name='LIM4-update'),
    url(r'^turnos/LIM5/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM5Update.as_view())),
                                              name='LIM5-update'),
    url(r'^turnos/LIM6/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.LIM6Update.as_view())),
                                              name='LIM6-update'),
    url(r'^turnos/EXT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.EXTUpdate.as_view())),
                                             name='EXT-update'),
    url(r'^turnos/TICS/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.TICSUpdate.as_view())),
        name='TICS-update'),
    url(r'^turnos/DES/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.DESUpdate.as_view())),
                                             name='DES-update'),
    url(r'^turnos/CAL/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.CALUpdate.as_view())),
                                             name='CAL-update'),
    url(r'^turnos/MEC/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.MECUpdate.as_view())),
                                             name='MEC-update'),
    url(r'^turnos/ML/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.MLUpdate.as_view())),
                                            name='ML-update'),
    url(r'^turnos/create/$', login_required(views.TurnoCreate.as_view()), name='turnos-create'),

lab/templates/lab/DES_calendar.html
{% include "lab/calendar.html" with listUrl="lab:DES-list" calendarUrl="lab:DES-calendar" %}

lab/templates/lab/LIM1_form.html
{% url 'lab:LIM1-list' as list_url %}
{% url 'lab:LIM1-update' object.id as update_url %}
{% include "lab/turno_form.html" with add_perm='lab.add_turno_LIM1' change_perm='lab.change_turno_LIM1' delete_perm='lab.delete_turno_LIM1' finish_perm='lab.finish_turno_LIM1' cancel_perm='lab.cancel_turno_LIM1' listUrl=list_url updateUrl=update_url %}

lab/templates/lab/LIM2_list.html
{% url 'lab:LIM2-list' as action_url %}
{% include "lab/turno_list.html" with listUrl='lab:LIM2-list' calendarUrl='lab:LIM2-calendar' createUrl='lab:LIM2-create' updateUrl='lab:LIM2-update' area_value='LIM2' add_perm='lab.add_turno_LIM2' change_perm='lab.change_turno_LIM2' delete_perm='lab.delete_turno_LIM2' finish_perm='lab.finish_turno_LIM2' cancel_perm='lab.cancel_turno_LIM2' postUrl=action_url %}

lab/templates/lab/LIM4_calendar.html
{% include "lab/calendar.html" with listUrl="lab:LIM4-list" calendarUrl="lab:LIM4-calendar" %}

lab/templates/lab/LIM4_list.html
{% url 'lab:LIM4-list' as action_url %}
{% include "lab/turno_list.html" with listUrl='lab:LIM4-list' calendarUrl='lab:LIM4-calendar' createUrl='lab:LIM4-create' updateUrl='lab:LIM4-update' area_value='LIM4' add_perm='lab.add_turno_LIM4' change_perm='lab.change_turno_LIM4' delete_perm='lab.delete_turno_LIM4' finish_perm='lab.finish_turno_LIM4' cancel_perm='lab.cancel_turno_LIM4' postUrl=action_url %}

lab/templates/lab/LIM5_calendar.html
{% include "lab/calendar.html" with listUrl="lab:LIM5-list" calendarUrl="lab:LIM5-calendar" %}

lab/templates/lab/LIM6_calendar.html
{% include "lab/calendar.html" with listUrl="lab:LIM6-list" calendarUrl="lab:LIM6-calendar" %}

lab/templates/lab/MEC_form.html
{% url 'lab:MEC-list' as list_url %}
{% url 'lab:MEC-update' object.id as update_url %}
{% include "lab/turno_form.html" with add_perm='lab.add_turno_MEC' change_perm='lab.change_turno_MEC' delete_perm='lab.delete_turno_MEC' finish_perm='lab.finish_turno_MEC' cancel_perm='lab.cancel_turno_MEC' updateUrl=update_url listUrl=list_url %}

lab/templates/lab/ML_form.html
{% url 'lab:ML-list' as list_url %}
{% url 'lab:ML-update' object.id as update_url %}
{% include "lab/turno_form.html" with add_perm='lab.add_turno_ML' change_perm='lab.change_turno_ML' delete_perm='lab.delete_turno_ML' finish_perm='lab.finish_turno_ML' cancel_perm='lab.cancel_turno_ML' updateUrl=update_url listUrl=list_url %}

lab/templates/lab/ML_list.html
{% url 'lab:ML-list' as action_url %}
{% include "lab/turno_list.html" with listUrl='lab:ML-list' calendarUrl='lab:ML-calendar' createUrl='lab:ML-create' updateUrl='lab:ML-update' area_value='ML' add_perm='lab.add_turno_ML' change_perm='lab.change_turno_ML' delete_perm='lab.delete_turno_ML' finish_perm='lab.finish_turno_ML' cancel_perm='lab.cancel_turno_ML' postUrl=action_url %}

lab/templates/lab/TICS_calendar.html
{% include "lab/calendar.html" with listUrl="lab:TICS-list" calendarUrl="lab:TICS-calendar" %}

lab/templates/lab/TICS_list.html
{% url 'lab:TICS-list' as action_url %}
{% include "lab/turno_list.html" with listUrl='lab:TICS-list' calendarUrl='lab:TICS-calendar' createUrl='lab:TICS-create' updateUrl='lab:TICS-update' area_value='TICS' add_perm='lab.add_turno_TICS' change_perm='lab.change_turno_TICS' delete_perm='lab.delete_turno_TICS' finish_perm='lab.finish_turno_TICS' cancel_perm='lab.cancel_turno_TICS' postUrl=action_url %}

lab/templates/lab/modals.html
<div class="modal fade" id="revWarning">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Revisionar Turno</h4>
            </div>
            <div class="modal-body" style="text-align:center">
            <h4>¿Está seguro que quiere revisionar el turno?</h4>
            <br/>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="revisionarTurno()">Aceptar</button>
            </div>
            <div class="modal-footer">

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

lab/templates/lab/turno_update_form.html
{% extends "intiSoft/base.html" %}

{% block head %}
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script>
        $(function() {
            $( ".datepicker" ).datepicker();
        });
    </script>
{% endblock %}

{% block content %}
    <form class="form-contact" style="padding-top:5%" action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group col-md-4">
                <label class="control-label" for="id_{{ field.name }}"> {{ field.label }} </label>
                {% if field.name == 'precio' %}
                    <div class="input-group">
                        <div class="input-group-addon">$</div>
                            {{ field }}
                    </div>
                {% elif field.name == 'area' %}
                    area: {{ field }}
                {% else %}
                    {{ field }}
                {% endif %}
                {% for error in field.errors %}
                    <div class="alert alert-error">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <div class="col-md-12">
            <input type="submit" value="Guardar"  class="btn btn-primary">
        </div>
        {% if form.errors %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-error">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
    </form>
{% endblock %}