adm/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control, never_cache

urlpatterns = [
    url(r'^contratos/OT/$', login_required(views.OTList.as_view()), name='ot-list'),
    url(r'^contratos/OT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTCreate.as_view())),
                                   name='ot-create'),
    url(r'^contratos/OT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTUpdate.as_view())),
                                               name='ot-update'),
    url(r'^contratos/OT-ML/$', login_required(views.OTMLList.as_view()), name='otml-list'),
    url(r'^contratos/OT-ML/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTMLCreate.as_view())),
                                      name='otml-create'),
    url(r'^contratos/OT-ML/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTMLUpdate.as_view())),
                                                  name='otml-update'),
    url(r'^contratos/SOT/$', login_required(views.SOTList.as_view()), name='sot-list'),
    url(r'^contratos/SOT/viewSOT/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.viewSOT)), name='sot-viewSOT'),
    url(r'^contratos/SOT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SOTCreate.as_view())),
                                    name='sot-create'),
    url(r'^contratos/SOT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SOTUpdate.as_view())),
                                                name='sot-update'),
    url(r'^contratos/RUT/$', login_required(views.RUTList.as_view()), name='rut-list'),
    url(r'^contratos/RUT/viewRUT/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.viewRUT)), name='rut-viewRUT'),
    url(r'^contratos/RUT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.RUTCreate.as_view())),
                                    name='rut-create'),
    url(r'^contratos/RUT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.RUTUpdate.as_view())),
                                                name='rut-update'),
    url(r'^contratos/SI/$', login_required(views.SIList.as_view()), name='si-list'),
    url(r'^contratos/SI/viewSI/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.viewSI)), name='si-viewSI'),
    url(r'^contratos/SI/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SICreate.as_view())),
                                   name='si-create'),
    url(r'^contratos/SI/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SIUpdate.as_view())),
                                               name='si-update'),
    url(r'^contratos/SI/(create|update/\d+)/OT_(?P<area>(LIA|LIM1|LIM2|LIM3|LIM4|LIM5|LIM6|EXT|DES|SIS|MEC|ML|CAL))/$', views.filterOT, name='filter-ot'),
    url(r'^presup/$', login_required(views.PresupuestoList.as_view()), name='presup-list'),
    url(r'^presup/viewWord/(?P<pk>\d+)/(?P<template>\w+)/$', never_cache(login_required(views.viewWord)), name='presup-viewWord'),
    #url(r'^presup/actBtn/(?P<pk>\d+)/$', 'adm.views.actualizar_precios', name='presup-actBtn'),
    url(r'^presup/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PresupuestoUpdate.as_view())),
                                         name='presup-update'),
    url(r'^presup/update/(?P<pk>\d+)/revision/', views.createRevision, name='presup-revision'),
    url(r'^presup/update/(?P<pk>\d+)/rollback/', views.rollBackRevision, name='presup-rollback'),
    url(r'^presup/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PresupuestoCreate.as_view())),
                             name='presup-create'),

    url(r'^presup/get_user/$', views.get_user, name='user-getdata'),
    url(r'^ofertatec/$', login_required(views.OfertaTecList.as_view()), name='ofertatec-list'),
    url(r'^ofertatec/delete/(?P<pk>\d+)/$', login_required(views.OfertaTecDelete.as_view()), name='ofertatec-delete'),
    url(r'^ofertatec/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OfertaTecUpdate.as_view())),
                                            name='ofertatec-update'),
    url(r'^ofertatec/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OfertaTecCreate.as_view())),
                                name='ofertatec-create'),

    url(r'^usuarios/$', login_required(views.UsuarioList.as_view()), name='usuarios-list'),
    url(r'^usuarios/delete/(?P<pk>\d+)/$', login_required(views.UsuarioDelete.as_view()), name='usuarios-delete'),
    url(r'^usuarios/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioUpdate.as_view())),
                                           name='usuarios-update'),
    url(r'^usuarios/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioCreate.as_view())),
                               name='usuarios-create'),
    url(r'^usuarios/create-modal/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioCreateModal.as_view())),
                               name='usuarios-create-modal'),
    url(r'^usuarios/update-modal/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioUpdateModal.as_view())),
                               name='usuarios-update-modal'),
    url(r'^pdt/$', login_required(views.PDTList.as_view()), name='pdt-list'),
    url(r'^pdt/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PDTCreate.as_view())),
                               name='pdt-create'),
    url(r'^pdt/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PDTUpdate.as_view())),
                                            name='pdt-update'),
    url(r'^pdt/detail/(?P<pk>\d+)/$', never_cache(login_required(views.PDTDetail.as_view())), name='pdt-detail'),
    url(r'^pdt/viewPDF/(?P<pk>\d+)/$', never_cache(views.pdtToPdf), name='pdt-viewPDF'),
    url(r'^pdt/viewXLS/(?P<pk>\d+)/$', never_cache(views.pdtToXls), name='pdt-viewXLS'),
    url(r'^contactos/create-modal/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.ContactoCreateModal.as_view())),
                                             name='contactos-create-modal'),
    url(r'^direcciones/create-modal/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.DireccionUsuarioCreateModal.as_view())),
                                             name='direcciones-create-modal'),
    url(r'^contactos/update-modal/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.ContactoUpdateModal.as_view())),
                                             name='contactos-update-modal'),
    url(r'^ajax/contactos/$', views.load_contactos, name='ajax_load_contactos'),
    url(r'^ajax/localides/$', views.load_localidades, name='ajax_load_localidades'),
    url(r'^ajax/direcciones/$', views.load_direcciones, name='ajax_load_direcciones'),
]

intiSoft/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .forms import MyAuthenticationForm
from . import views as myViews
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^lab/', include('lab.urls', namespace="lab")),
    url(r'^adm/', include('adm.urls', namespace="adm")),
    url(r'^recent_activity/', include('activity_log.urls', namespace="activity_log")),
    url(r'^login/$', views.login,
        {'template_name': 'intiSoft/login.html',
        'authentication_form': MyAuthenticationForm},
        name='user-login'),
    url(r'^logout/$', views.logout,
        {'template_name': 'intiSoft/logout.html'},
        name='user-logout'),
    url('^$', myViews.index, name='index'),
    url(r'^profile/(?P<pk>\d+)/$', myViews.ProfileView.as_view(),
        name='user-profile'),
    url(r'^ofertatec_autocomplete/', myViews.ofertatec_autocomplete, name='ofertatec_autocomplete'),
    #url(r'^simple-autocomplete/', include('simple_autocomplete.urls', namespace='simple_autocomplete'))
]

adm/templates/adm/direccion_modal.html
{% extends "intiSoft/base.html" %}

{% block head %}
    {% load staticfiles %}
    <script type="text/javascript" src="{% static 'intiSoft/js/jquery.formset.js' %}"></script>
    <script>
        $(function() {
            $("#id_usuario").val("{{ parent_id }}");

            $("#id_provincia").on('change', function (e) {

                // Actualizo las localidades de la provincia seleccionada
                var url = $("#direccionForm").attr("data-localidades-url");
                var provinciaId = $(this).val();

                $.ajax({
                    url: url,
                    data: { 'provincia': provinciaId },
                    success: function(data) {
                                $("#id_localidad").html(data);
                    }
                });

                $("#id_localidad").trigger('change');

            });
        });
    </script>
{% endblock %}

{% block content %}
{% load intiSoft_filters %}
<div class="row">
    {% if form.errors %}
        <div class="col-md-offset-1 col-md-10 bs-callout bs-callout-danger">
            <h3>Error!</h3>
            <strong> Hay problemas con los siguientes campos: </strong><br/>
            <ul>
            {% for key, errors in form.errors.items %}
                {% if key == '__all__' %}
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% else %}
                    <li>{% get_verbose_name form.instance key %}
                {% endif %}
            {% endfor %}
            </ul>
        </div>
    {% endif %}
</div>
<h2 class="text-danger">Nueva Direccion</h2>
<div class="row">
    <div class="col-md-12 col-xs-12">
        <form id="direccionForm" class="form-horizontal" style="padding-top:5%" action=""
              method="{% if edit %}POST{% else %}GET{% endif %}" data-localidades-url="{% url 'adm:ajax_load_localidades' %}">
            <div class="col-md-12 col-xs-12">
                {% csrf_token %}

                <input type="hidden" name="_popup" value="1">
                <div class="col-md-6 col-xs-offset-3 col-xs-6">
                    <!-- Usuario -->
                    <div class="form-group">
                        <label class="control-label col-md-2 col-xs-3" style="text-align:left"
                         for="id_usuario">
                            Usuario
                        </label>
                        <div class="col-md-8 col-xs-9">
                            {{ form.usuario | disable }}
                            <input type="hidden" name="usuario" value="{{parent_id}}">
                        </div>
                    </div>
                    <!-- Nombre -->
                    <div class="form-group">
                        <label class="control-label col-md-2 col-xs-3" style="text-align:left"
                         for="id_provincia">
                            Provincia
                        </label>
                        <div class="col-md-8 col-xs-9">
                            {% if edit %}
                                {{ form.provincia }}
                                {% for error in form.provincia.errors %}
                                    <div class="alert alert-error">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% else %}
                                {{ form.provincia | disable }}
                            {% endif %}
                        </div>
                    </div>
                    <!-- Localidad -->
                    <div class="form-group">
                        <label class="control-label col-md-2 col-xs-3" style="text-align:left"
                         for="id_localidad">
                            Localidad
                        </label>
                        <div class="col-md-8 col-xs-9">
                            {% if edit %}
                                {{ form.localidad }}
                                {% for error in form.localidad.errors %}
                                    <div class="alert alert-error">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% else %}
                                {{ form.localidad | disable }}
                            {% endif %}
                        </div>
                    </div>
                    <!-- Calle -->
                    <div class="form-group">
                        <label class="control-label col-md-2 col-xs-3" style="text-align:left"
                         for="id_calle">
                            Calle
                        </label>
                        <div class="col-md-8 col-xs-9">
                            {% if edit %}
                                {{ form.calle }}
                                {% for error in form.calle.errors %}
                                    <div class="alert alert-error">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% else %}
                                {{ form.calle | disable }}
                            {% endif %}
                        </div>
                    </div>
                    <!-- Numero -->
                    <div class="form-group">
                        <label class="control-label col-md-2 col-xs-3" style="text-align:left"
                         for="id_calle">
                            Número
                        </label>
                        <div class="col-md-3 col-xs-4">
                            {% if edit %}
                                {{ form.numero }}
                                {% for error in form.numero.errors %}
                                    <div class="alert alert-error">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% else %}
                                {{ form.numero | disable }}
                            {% endif %}
                        </div>
                        <label class="control-label col-md-2 col-xs-2" style="text-align:left"
                         for="id_piso">
                            Piso
                        </label>
                        <div class="col-md-3 col-xs-3">
                            {% if edit %}
                                {{ form.piso }}
                                {% for error in form.piso.errors %}
                                    <div class="alert alert-error">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% else %}
                                {{ form.piso | disable }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    {% if create %}
    <div class="col-md-2">
        <input type="submit" value="Guardar" class="btn btn-danger" style="float:right" form="direccionForm">
    </div>
    {% endif %}
</div>
{% endblock %}

adm/templates/adm/ofertatec_confirm_delete.html
{% extends "intiSoft/base.html" %}

{% block content %}
<div style="margin-top:10%; text-align:center">
    <form action="" method="post">{% csrf_token %}
        <p class="lead">¿Está seguro que quiere eliminar el registro?</p>
        <input type="submit" class="btn btn-danger" value="Confirmar" />
        <input type="submit" class="btn btn-warning" name="cancelar" value="Cancelar" />
    </form>
</div>
{% endblock %}

adm/templates/adm/pdt_detail.html
{% load static %}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">&times;</button>
    </button>
    <h4 class="title text-danger">{{ pdt.nombre }}</h4>
</div>
<div class="modal-body">
    <table class="table">
        <thead>
        <tr>
            <th style="text-align:center" scope="col">Tipo</th>
            <th style="text-align:center" scope="col">Número</th>
            <th style="text-align:center" scope="col">Servicios</th>
            <th style="text-align:center" scope="col">Importe Bruto</th>
            <th style="text-align:center" scope="col">Importe Neto</th>
            <th style="text-align:center" scope="col">Importe Facturado</th>
        </tr>
        </thead>
    <tbody>
        {% for ot in pdt.ot_set.all %}
            <tr style="text-align:center">
                <td>OT</td>
                <td><a class="ref" href="{% url 'adm:ot-update' ot.id %}" target="_blank">{{ ot.codigo }}</a></td>
                <td>{{ ot.get_servicios }}</td>
                <td>${{ ot.importe_bruto }}</td>
                <td>${{ ot.importe_neto }}</td>
                <td>${{ ot.get_facturacion }}</td>
            </tr>
        {% endfor %}
        {% for otml in pdt.otml_set.all %}
            <tr style="text-align:center">
                <td>OTML</td>
                <td><a class="ref" href="{% url 'adm:otml-update' otml.id %}" target="_blank">{{ otml.codigo }}</a></td>
                <td>{{ otml.get_servicios }}</td>
                <td>${{ otml.importe_bruto }}</td>
                <td>${{ otml.importe_neto }}</td>
                <td>${{ otml.get_facturacion }}</td>
            </tr>
        {% endfor %}
        {% for sot in pdt.sot_set.all %}
            <tr style="text-align:center">
                <td>SOT</td>
                <td><a class="ref" href="{% url 'adm:sot-update' sot.id %}" target="_blank">{{ sot.codigo }}</a></td>
                <td>{{ sot.get_servicios }}</td>
                <td>${{ sot.importe_bruto }}</td>
                <td>${{ sot.importe_neto }}</td>
                <td>${{ sot.get_facturacion }}</td>
            </tr>
        {% endfor %}
        {% for rut in pdt.rut_set.all %}
            <tr style="text-align:center">
                <td>RUT</td>
                <td><a class="ref" href="{% url 'adm:rut-update' rut.id %}" target="_blank">{{ rut.codigo }}</a></td>
                <td>{{ rut.get_servicios }}</td>
                <td>${{ rut.importe_bruto }}</td>
                <td>${{ rut.importe_neto }}</td>
                <td>${{ rut.get_facturacion }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
<div class="modal-footer">
    <a href="{% url 'adm:pdt-viewXLS' pdt.id %}">
        <img style="width: 30px" src="{% static 'intiSoft/img/xls.png' %}"/>
    </a>
    <a href="{% url 'adm:pdt-viewPDF' pdt.id %}">
        <img style="width: 30px" src="{% static 'intiSoft/img/pdf.png' %}"/>
    </a>
</div>

adm/templates/adm/rut_list.html
{% extends "intiSoft/base.html" %}
{% block content %}
{% load intiSoft_filters %}
<div class="row">
    <div class="col-md-offset-6 col-md-6">
        {% include "intiSoft/paginator.html" %}
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <a href="{% url 'adm:rut-create' %}">
            <button type="button" class="btn btn-danger"
            {% if 'adm.add_rut' not in user.get_all_permissions %}
            disabled
            {% endif %}>Crear</button>
        </a>
    </div>
    <div class="col-md-6 col-md-offset-1">
        <form name="searchForm" class="search-bar" action="" method="GET">
            <div class="input-group">
                <div class="input-group-btn">
                    <button id="calendarBtn" type="button"class="btn btn-search btn-default">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </button>
                </div>
                <input id="searchField" name="search" type="text" class="form-control" data-role="tagsinput">
                <div class="input-group-btn">
                    <button type="submit" value="submit" class="btn btn-search btn-default">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-12">
        <table id="rutTable" class="table table-hover table-pointer">
            <caption>Planilla de RUTs</caption>
            <thead>
                {% for name, label in fields %}
                    <td>
                        {% if name in "estado" %}
                            {{ label }}
                        {% else %}
                            <div class="dropdown">
                                <span class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false"> {{ label }}
                                   <span class="caret"></span>
                                </span>
                                <ul id="{{'drop-'|add:forloop.counter}}" class="dropdown-menu">
                                    <li><a name="order_by" href="{{ '?order_by='|add:name|add:'&'|add:request.GET.urlencode }}">Orden ascendente</a></li>
                                    <li><a name="order_by" href="{{ '?order_by=-'|add:name|add:'&'|add:request.GET.urlencode }}">Orden descendente</a></li>
                                </ul>
                            </div>
                        {% endif %}
                    </td>
                {% endfor %}
            <td></td>
            <td></td>
            <td></td>
            </thead>
            <tbody>
                {% for rut in rut_list %}
                        <tr
                            {% if 'adm.read_rut' in user.get_all_permissions %}
                                onclick="if (trlink) {location.href='{% url 'adm:rut-update' rut.id %}'}"
                            {% endif %}
                            class = {% if rut.estado == 'borrador' %} "neutral"
                                      {% elif rut.estado == 'cobrada' %} "success"
                                      {% elif rut.estado == 'pendiente' %} "warning"
                                      {% elif rut.estado == 'cancelada' %} "danger"
                                    {% endif %}
                        >
                        <td></td>
                        <td>{{ rut.codigo }}</td>
                        <td>{{ rut.fecha_realizado | date | default_if_none:"" }}</td>
                        <td>{{ rut.deudor }}</td>
                        <td>{{ rut.solicitante }}</td>
                        <td>${{ rut.importe_bruto | floatformat }}</td>
                        <td>${{ rut.importe_neto | floatformat }}</td>
                        <td>{{ rut.fecha_envio_ut | date | default_if_none:"" }}</td>
                        <td>{{ rut.firmada | boolToText }}</td>
                        <td>{{ rut.fecha_envio_cc | date | default_if_none:"" }}</td>
                        <td>
                            <button onclick="trlink=false;" title="Cobrada" data-action="Finalizar"
                                data-model="RUT" type="button" class="btn btn-default"
                                data-id={{rut.id}} data-toggle="modal" data-target="#myModal"
                                {% if rut.estado != "pendiente" or 'adm.finish_rut' not in user.get_all_permissions or rut.get_area not in userGroups %}
                                    disabled
                                {% endif %}>
                                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                            </button>
                        </td>
                        <td>
                            <button onclick="trlink=false;" title="Cancelar" data-action="Cancelar"
                                data-model="RUT" type="button" class="btn btn-default"
                                data-id={{rut.id}} data-toggle="modal" data-target="#textBoxModal"
                                {% if rut.estado in "['cobrada', 'cancelada']" or 'adm.cancel_rut' not in user.get_all_permissions or rut.get_area not in userGroups %}
                                    disabled
                                {% endif %}>
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </button>
                        </td>
                        <td>
                            <button onclick="trlink=false;" title="Eliminar" data-action="Eliminar"
                                data-model="RUT" type="button" class="btn btn-default"
                                data-id={{rut.id}} data-toggle="modal" data-target="#myModal"
                                {% if 'adm.delete_rut' not in user.get_all_permissions or rut.get_area not in userGroups %}
                                    disabled
                                {% endif %}>
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <table style="margin: 0 auto">
            <td><div id="ref" class="alert-neutral">&nbsp;</div>Borrador</td>
            <td><div id="ref" class="alert-warning">&nbsp;</div>Pendiente</td>
            <td><div id="ref" class="alert-success">&nbsp;</div>Cobrada</td>
            <td><div id="ref" class="alert-danger">&nbsp;</div>Cancelada</td>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-offset-6 col-md-6">
        {% include "intiSoft/paginator.html" %}
    </div>
</div>
<br/>
<br/>
{% include "intiSoft/modals.html" %}
{% endblock %}

adm/templates/adm/usuario_list.html
{% extends "intiSoft/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-offset-6 col-md-6">
        {% include "intiSoft/paginator.html" %}
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <a href="{% url 'adm:usuarios-create' %}">
            <button type="button" class="btn btn-danger"
            {% if 'adm.add_usuario' not in user.get_all_permissions %}
            disabled
            {% endif %}>Crear</button>
        </a>
    </div>
    <div class="col-md-6 col-md-offset-1">
        <form name="searchForm" class="search-bar" action="" method="GET">
            <div class="input-group">
                <input id="searchField" name="search" type="text" class="form-control" data-role="tagsinput">
                <div class="input-group-btn">
                    <button type="submit" value="submit" class="btn btn-search btn-default">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-12">
        <table id="usuarioTable" class="table table-hover table-pointer">
            <caption>Planilla de usuarios</caption>
            <thead>
                {% for name, label in fields %}
                    <td>
                        <div class="dropdown">
                            <span class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false"> {{ label }}
                               <span class="caret"></span>
                            </span>
                            <ul id="{{'drop-'|add:forloop.counter}}" class="dropdown-menu">
                                <li><a name="order_by" href="{{ '?order_by='|add:name|add:'&'|add:request.GET.urlencode }}">Orden ascendente</a></li>
                                <li><a name="order_by" href="{{ '?order_by=-'|add:name|add:'&'|add:request.GET.urlencode }}">Orden descendente</a></li>
                            </ul>
                        </div>
                    </td>
                {% endfor %}
            <td></td>
            </thead>
            <tbody>
                {% for usuario in usuario_list %}
                    <tr
                        {% if 'adm.change_usuario' in user.get_all_permissions %}
                            onclick="if (trlink) {location.href='{% url 'adm:usuarios-update' usuario.id %}'}"
                        {% endif %}
                    >
                        <td>{{ usuario.nro_usuario }}</td>
                        <td>{{ usuario.nombre }}</td>
                        <td>{{ usuario.cuit }}</td>
                        <td>{{ usuario.mail | default_if_none:"" }}</td>
                        <td>{{ usuario.rubro }}</td>
                        <td>
                            <button onclick="trlink=false;" title="Eliminar" data-action="Eliminar"
                                data-model="usuario" type="button" class="btn btn-default"
                                data-id={{usuario.id}} data-toggle="modal" data-target="#myModal"
                                {% if 'adm.delete_usuario' not in user.get_all_permissions %}
                                disabled
                                {% endif %}>
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-offset-6 col-md-6">
        {% include "intiSoft/paginator.html" %}
    </div>
</div>
{% include "intiSoft/modals.html" %}
{% endblock %}