adm/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control, never_cache

urlpatterns = [
    url(r'^contratos/OT/$', login_required(views.OTList.as_view()), name='ot-list'),
    url(r'^contratos/OT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTCreate.as_view())),
                                   name='ot-create'),
    url(r'^contratos/OT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTUpdate.as_view())),
                                               name='ot-update'),
    url(r'^contratos/OT-ML/$', login_required(views.OTMLList.as_view()), name='otml-list'),
    url(r'^contratos/OT-ML/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTMLCreate.as_view())),
                                      name='otml-create'),
    url(r'^contratos/OT-ML/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OTMLUpdate.as_view())),
                                                  name='otml-update'),
    url(r'^contratos/SOT/$', login_required(views.SOTList.as_view()), name='sot-list'),
    url(r'^contratos/SOT/viewSOT/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.viewSOT)), name='sot-viewSOT'),
    url(r'^contratos/SOT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SOTCreate.as_view())),
                                    name='sot-create'),
    url(r'^contratos/SOT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SOTUpdate.as_view())),
                                                name='sot-update'),
    url(r'^contratos/RUT/$', login_required(views.RUTList.as_view()), name='rut-list'),
    url(r'^contratos/RUT/viewRUT/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.viewRUT)), name='rut-viewRUT'),
    url(r'^contratos/RUT/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.RUTCreate.as_view())),
                                    name='rut-create'),
    url(r'^contratos/RUT/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.RUTUpdate.as_view())),
                                                name='rut-update'),
    url(r'^contratos/SI/$', login_required(views.SIList.as_view()), name='si-list'),
    url(r'^contratos/SI/viewSI/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.viewSI)), name='si-viewSI'),
    url(r'^contratos/SI/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SICreate.as_view())),
                                   name='si-create'),
    url(r'^contratos/SI/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.SIUpdate.as_view())),
                                               name='si-update'),
    url(r'^contratos/SI/(create|update/\d+)/OT_(?P<area>(LIA|LIM1|LIM2|LIM3|LIM4|LIM5|LIM6|EXT|DES|SIS|MEC|ML|CAL))/$', views.filterOT, name='filter-ot'),
    url(r'^presup/$', login_required(views.PresupuestoList.as_view()), name='presup-list'),
    url(r'^presup/viewWord/(?P<pk>\d+)/(?P<template>\w+)/$', never_cache(login_required(views.viewWord)), name='presup-viewWord'),
    #url(r'^presup/actBtn/(?P<pk>\d+)/$', 'adm.views.actualizar_precios', name='presup-actBtn'),
    url(r'^presup/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PresupuestoUpdate.as_view())),
                                         name='presup-update'),
    url(r'^presup/update/(?P<pk>\d+)/revision/', views.createRevision, name='presup-revision'),
    url(r'^presup/update/(?P<pk>\d+)/rollback/', views.rollBackRevision, name='presup-rollback'),
    url(r'^presup/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PresupuestoCreate.as_view())),
                             name='presup-create'),

    url(r'^presup/get_user/$', views.get_user, name='user-getdata'),
    url(r'^ofertatec/$', login_required(views.OfertaTecList.as_view()), name='ofertatec-list'),
    url(r'^ofertatec/delete/(?P<pk>\d+)/$', login_required(views.OfertaTecDelete.as_view()), name='ofertatec-delete'),
    url(r'^ofertatec/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OfertaTecUpdate.as_view())),
                                            name='ofertatec-update'),
    url(r'^ofertatec/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.OfertaTecCreate.as_view())),
                                name='ofertatec-create'),

    url(r'^usuarios/$', login_required(views.UsuarioList.as_view()), name='usuarios-list'),
    url(r'^usuarios/delete/(?P<pk>\d+)/$', login_required(views.UsuarioDelete.as_view()), name='usuarios-delete'),
    url(r'^usuarios/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioUpdate.as_view())),
                                           name='usuarios-update'),
    url(r'^usuarios/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioCreate.as_view())),
                               name='usuarios-create'),
    url(r'^usuarios/create-modal/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioCreateModal.as_view())),
                               name='usuarios-create-modal'),
    url(r'^usuarios/update-modal/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.UsuarioUpdateModal.as_view())),
                               name='usuarios-update-modal'),
    url(r'^pdt/$', login_required(views.PDTList.as_view()), name='pdt-list'),
    url(r'^pdt/create/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PDTCreate.as_view())),
                               name='pdt-create'),
    url(r'^pdt/update/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.PDTUpdate.as_view())),
                                            name='pdt-update'),
    url(r'^pdt/detail/(?P<pk>\d+)/$', never_cache(login_required(views.PDTDetail.as_view())), name='pdt-detail'),
    url(r'^pdt/viewPDF/(?P<pk>\d+)/$', never_cache(views.pdtToPdf), name='pdt-viewPDF'),
    url(r'^pdt/viewXLS/(?P<pk>\d+)/$', never_cache(views.pdtToXls), name='pdt-viewXLS'),
    url(r'^contactos/create-modal/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.ContactoCreateModal.as_view())),
                                             name='contactos-create-modal'),
    url(r'^direcciones/create-modal/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.DireccionUsuarioCreateModal.as_view())),
                                             name='direcciones-create-modal'),
    url(r'^contactos/update-modal/(?P<pk>\d+)/$', cache_control(max_age=0, no_cache=True, no_store=True)(login_required(views.ContactoUpdateModal.as_view())),
                                             name='contactos-update-modal'),
    url(r'^ajax/contactos/$', views.load_contactos, name='ajax_load_contactos'),
    url(r'^ajax/localides/$', views.load_localidades, name='ajax_load_localidades'),
    url(r'^ajax/direcciones/$', views.load_direcciones, name='ajax_load_direcciones'),
]

intiSoft/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .forms import MyAuthenticationForm
from . import views as myViews
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^lab/', include('lab.urls', namespace="lab")),
    url(r'^adm/', include('adm.urls', namespace="adm")),
    url(r'^recent_activity/', include('activity_log.urls', namespace="activity_log")),
    url(r'^login/$', views.login,
        {'template_name': 'intiSoft/login.html',
        'authentication_form': MyAuthenticationForm},
        name='user-login'),
    url(r'^logout/$', views.logout,
        {'template_name': 'intiSoft/logout.html'},
        name='user-logout'),
    url('^$', myViews.index, name='index'),
    url(r'^profile/(?P<pk>\d+)/$', myViews.ProfileView.as_view(),
        name='user-profile'),
    url(r'^ofertatec_autocomplete/', myViews.ofertatec_autocomplete, name='ofertatec_autocomplete'),
    #url(r'^simple-autocomplete/', include('simple_autocomplete.urls', namespace='simple_autocomplete'))
]

intiSoft/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.models import User


class MyAuthenticationForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(MyAuthenticationForm, self).__init__(*args, **kwargs)

        #self.base_fields['username'].widget.attrs['class'] = 'form-control'
        self.base_fields['username'].widget.attrs['placeholder'] = 'Usuario'

        #self.base_fields['password'].widget.attrs['class'] = 'form-control'
        self.base_fields['password'].widget.attrs['placeholder'] = 'Contraseña'


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs['instance']
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['old_password'].widget.attrs['class'] = 'form-control'
        self.fields['old_password'].widget.attrs['type'] = 'password'
        self.fields['old_password'].widget.attrs['disabled'] = True
        self.fields['new_password'].widget.attrs['class'] = 'form-control'
        self.fields['new_password'].widget.attrs['disabled'] = True
        self.fields['cnew_password'].widget.attrs['class'] = 'form-control'
        self.fields['cnew_password'].widget.attrs['disabled'] = True

    def clean_username(self):
        return self.instance.username

    def clean_old_password(self):
        password = self.cleaned_data.get('old_password', None)
        if password:
            if not self.user.check_password(password):
                msg = "Contraseña incorrecta."
                self._errors['old_password'] = self.error_class([msg])
            else:
                return password
        return password

    def clean_cnew_password(self):
        new_password = self.cleaned_data.get('new_password', None)
        cnew_password = self.cleaned_data.get('cnew_password', None)
        if new_password != cnew_password:
            msg = "La constraseña no coincide."
            self._errors['cnew_password'] = self.error_class([msg])
        elif new_password and cnew_password:
            if len(new_password) < 2 or len(new_password) > 8:
                msg = "La contraseña debe tener entre 4 y 8 caracteres."
                self._errors['new_password'] = self.error_class([msg])
            if len(cnew_password) < 2 or len(cnew_password) > 8:
                msg = "La contraseña debe tener entre 4 y 8 caracteres."
                self._errors['cnew_password'] = self.error_class([msg])
            self.user.set_password(new_password)
        return cnew_password

    old_password = forms.CharField(max_length=10, widget=forms.PasswordInput, required=False)
    new_password = forms.CharField(max_length=10, widget=forms.PasswordInput, required=False)
    cnew_password = forms.CharField(max_length=10, widget=forms.PasswordInput, required=False)

    class Meta:
        model = User
        fields = ['username',
                  'email',
                  'first_name',
                  'last_name',
                 ]

intiSoft/views.py
# -*- coding: utf-8 -*-
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic import UpdateView

from adm.models import OfertaTec_Descripcion
from .forms import ProfileForm
from django.core.urlresolvers import reverse_lazy


def is_member(user, groupName):
    return user.groups.filter(name=groupName).exists()


@login_required
def index(request):
    user = request.user
    #Chequeo el grupo al que pertenece el usuario
    if is_member(user, 'Administracion'):
        return redirect('adm/presup')
    elif is_member(user, 'LIA'):
        return redirect('lab/turnos/LIA')
    elif is_member(user, 'LIM1'):
        return redirect('lab/turnos/LIM1')
    elif is_member(user, 'LIM2'):
        return redirect('lab/turnos/LIM2')
    elif is_member(user, 'LIM3'):
        return redirect('lab/turnos/LIM3')
    elif is_member(user, 'LIM6'):
        return redirect('lab/turnos/LIM6')
    elif is_member(user, 'EXT'):
        return redirect('lab/turnos/EXT')
    elif is_member(user, 'SIS'):
        return redirect('lab/turnos/SIS')
    elif is_member(user, 'DES'):
        return redirect('lab/turnos/DES')
    return redirect('adm/presup')


class ProfileView(UpdateView):
    model = User
    template_name = 'intiSoft/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('index')
    #slug_url_kwarg = 'username'
    #slug_field = 'username'


def ofertatec_autocomplete(request):
    if request.GET.get('q'):
        q = request.GET['q']
        data = OfertaTec_Descripcion.objects.filter(detalle__icontains=q)\
                                            .values_list('id', 'detalle')
        json = list(data)
        print json
        return JsonResponse(json, safe=False)
    else:
        HttpResponse("No cookies")

intiSoft/templates/intiSoft/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'intiSoft/css/auth.css' %}"/>
<!--
    <script type="text/javascript" src="{% static 'intiSoft/js/auth.js' %}"></script>
-->
    {% block head %}{% endblock%}
</head>

<body>
    <div class="wrapper">
        <div id="content" class="container">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

intiSoft/templates/intiSoft/auth_old.html
<!--
{% block content %}
    <div class="row">
        <div id="login" class="col-md-4 col-md-offset-4" style="margin-top: 10%">
            <br/>
            <br/>
            {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
            {% endif %}

            {% if next %}
                {% if user.is_authenticated %}
                <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
                {% else %}
                <p>Please login to see this page.</p>
                {% endif %}
            {% endif %}

            <form class="form-contact" method="post" action="{% url 'user-login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label" for="id_{{ form.username.name }}"> Usuario </label>
                    {{ form.username }}
                </div>
                <div class="form-group">
                    <label class="control-label" for="id_{{ form.password.name }}"> Contraseña </label>
                    {{ form.password }}
                </div>
            <input type="submit" value="Iniciar"  class="btn btn-primary">
            <input type="hidden" name="next" value="{{ next }}" />
            </form>
            <br/>
            <br/>
        </div>
    </div>
{% endblock %}
-->

intiSoft/templates/intiSoft/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'intiSoft/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'intiSoft/css/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'intiSoft/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'intiSoft/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'intiSoft/css/bootstrap-tagsinput.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'intiSoft/css/daterangepicker.css' %}" />
    <script type="text/javascript" src="{% static 'intiSoft/js/jquery-1.10.2.js' %}"></script>
    <script type="text/javascript" src="{% static 'intiSoft/js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'intiSoft/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'intiSoft/js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'intiSoft/js/csrftoken.js' %}"></script>
    <script type="text/javascript" src="{% static 'intiSoft/js/bootstrap-tagsinput.js' %}"></script>
    <script type="text/javascript" src="{% static 'intiSoft/js/base.js' %}"></script>
    <script type="text/javascript" src="{% static 'intiSoft/js/moment.js' %}"></script>
    <script type="text/javascript" src="{% static 'intiSoft/js/daterangepicker.js' %}"></script>
    {% block head %}{% endblock%}

    {% if not popup %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="https://www.inti.gob.ar/">INTI</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    {% block nav %}{% endblock %}
                    {% include "adm/nav_buttons.html" %}
                    {% include "lab/nav_buttons.html" %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> {{ user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'user-profile' user.id %}">Perfil</a></li>
                            <li><a href="{% url 'user-logout' %}">Cerrar sesión</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    {% endif %}
</head>

<body>
    <div id="content" style="margin-left:2%; margin-right: 2%">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

intiSoft/templates/intiSoft/homepage.html
{% extends "intiSoft/base.html" %}

{% block content %}
    <p>{% {{ user.perms }} %]</p>
{% endblock %}

intiSoft/templates/intiSoft/login.html
{% extends "intiSoft/auth.html" %}

{% block content %}
        <h1>Bienvenido</h1>
        {% if form.errors %}
        <p>Su usuario y contraseña no coinciden, intente nuevamente.</p>
        {% endif %}

        {% if next %}
            {% if user.is_authenticated %}
            <p>No tiene permiso para ver esta página, logueese con un usuario adecuado.</p>
            {% endif %}
        {% endif %}

        <form class="form" method="post" action="{% url 'user-login' %}">
            {% csrf_token %}
            {{ form.username }}
            {{ form.password }}
            <button type="submit" id="login-button">Iniciar</button>
            <input type="hidden" name="next" value="{{ next }}" />
        </form>
{% endblock %}

intiSoft/templates/intiSoft/logout.html
{% extends "intiSoft/auth.html" %}

{% block head %}
    <meta http-equiv="refresh" content="3;url={% url 'user-login' %}" />
{% endblock %}

{% block content %}
<div style="margin-top:10%">
    <p class="lead text-center">Ha cerrado sesión satisfactoriamente, en breve será redirigido.</p>
</div>
{% endblock %}

intiSoft/templates/intiSoft/modals.html
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body" style="text-align:center">
            <h4></h4>
            <p></p>
            <br/>
                <form id="myForm" action={% if postUrl %}{{postUrl}}{% else %}''{% endif %} method="POST">
                {% csrf_token %}
                    <input id="inputField" type="hidden" name="action" value="id"></input>
                    <button id="cancelButton" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button id="submitButton" type="submit" class="btn btn-primary" name="name" value="value">Aceptar</button>
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="textBoxModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body" style="text-align:center">
            <h4></h4>
            <p></p>
            <br/>
                <form id="textBoxModalForm" action={% if postUrl %}{{postUrl}}{% else %}''{% endif %} method="POST">
                {% csrf_token %}
                    <div class="form-group">
                        <input id="inputField2" type="hidden" name="action" value="id"></input>
                        <label for="textarea" style="float: left">Especifique el motivo:</label>
                        <textarea class="form-control" id="textarea" name="observations" rows="3"></textarea>
                        <label class="error"></label>
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button id="submitBtn" disabled type="submit" class="btn btn-primary" name="name" value="value">Aceptar</button>
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="myErrorModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Error</h4>
            </div>
            <div class="modal-body" style="text-align:center">
            <h4></h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

intiSoft/templates/intiSoft/profile.html
{% extends "intiSoft/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-offset-1 col-md-10">
        <!-- Separador -->
        <div class="col-md-12" style="border-top: 3px solid #eee"/>
        <!-- Titulo -->
        <div class="col-md-12">
            <h2 class="text-danger">Mi Perfil</h2>
        </div>
        <!-- Separador -->
        <div class="col-md-12" style="border-top: 1.5px solid #eee"/>
        <div class="col-md-12">
            <form class="form-horizontal" style="padding-top:5%" action="" method="POST">
                {% csrf_token %}
                <div class="col-md-6">
                    <!-- Nombre -->
                    <div class="form-group">
                        <label class="control-label col-md-6" style="text-align:left"
                          for="id_first_name">
                            Nombre
                        </label>
                        <div class="col-md-6">
                           {{ form.first_name}}
                           {% for error in form.first_name.errors %}
                               <div class="alert alert-error">
                                   <strong>{{ error|escape }}</strong>
                               </div>
                           {% endfor %}
                        </div>
                    </div>
                    <!-- Apellido -->
                    <div class="form-group">
                        <label class="control-label col-md-6" style="text-align:left"
                          for="id_last_name">
                            Apellido
                        </label>
                        <div class="col-md-6">
                           {{ form.last_name}}
                           {% for error in form.last_name.errors %}
                               <div class="alert alert-error">
                                   <strong>{{ error|escape }}</strong>
                               </div>
                           {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <!-- Usuario -->
                    <div class="form-group">
                        <label class="control-label col-md-5" style="text-align:left"
                         for="id_usuario">
                            Usuario
                        </label>
                        <div class="col-md-6">
                           {{ form.username }}
                           {% for error in form.username.errors %}
                               <div class="alert alert-error">
                                   <strong>{{ error|escape }}</strong>
                               </div>
                           {% endfor %}
                        </div>
                    </div>
                    <!-- Email -->
                    <div class="form-group">
                        <label class="control-label col-md-5" style="text-align:left"
                          for="id_email">
                            Email
                        </label>
                        <div class="col-md-6">
                           {{ form.email}}
                           {% for error in form.email.errors %}
                               <div class="alert alert-error">
                                   <strong>{{ error|escape }}</strong>
                               </div>
                           {% endfor %}
                        </div>
                    </div>
                </div>
                <!-- Separador -->
                <div class="col-md-12" style="border-top: 1.5px solid #eee"/>
                </br>
                <!-- Password -->
                <div class="col-md-6" style="padding-left:0px">
                    <div class="form-group">
                        <label class="control-label col-md-6" style="text-align:left"
                          for="id_old_password">
                            Contraseña
                        </label>
                        <div class="col-md-6">
                           {{ form.old_password}}
                           {% for error in form.old_password.errors %}
                               <div class="alert alert-error">
                                   <strong>{{ error|escape }}</strong>
                               </div>
                           {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-6" style="text-align:left"
                          for="id_new_password">
                            Nueva contraseña
                        </label>
                        <div class="col-md-6">
                           {{ form.new_password}}
                           {% for error in form.new_password.errors %}
                               <div class="alert alert-error">
                                   <strong>{{ error|escape }}</strong>
                               </div>
                           {% endfor %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-6" style="text-align:left"
                          for="id_cnew_password">
                            Confirmar contraseña
                        </label>
                        <div class="col-md-6">
                           {{ form.cnew_password}}
                           {% for error in form.cnew_password.errors %}
                               <div class="alert alert-error">
                                   <strong>{{ error|escape }}</strong>
                               </div>
                           {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <button id="change_pass" class="btn btn-warning">Cambiar contraseña</button>
                </div>
                {% if form.errors %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-error">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="col-md-12">
                    <br/>
                    <br/>
                    <br/>
                    <div class="col-md-2">
                        <input type="submit" value="Guardar"  class="btn btn-danger">
                    </div>
                    <div class="col-md-2">
                        <button type="button" class="btn btn-default" onclick="window.history.back()">
                        Volver</button>
                    </div>
                    <br/>
                    <br/>
                    <br/>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}